Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/09/2023
Var
   // Seção de Declarações das variáveis

i: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
    i <- 1
    enquanto (i <= 10) faca
    escreva(i)
    i <- i + 1
    fimenquanto

Fimalgoritmo